Ficzer | admin console
Majkoo/PicturesUI pull request #22
Opened 2024-07-24 17:49 UTC by lasgra

New ficzer, I've made modern looking table using ostatni krzyk mody of styling 
![image](https://github.com/user-attachments/assets/5e25b4b3-a444-4759-b41f-be570141a95a)
![image](https://github.com/user-attachments/assets/d927ca2b-d628-4c6e-a829-affe152287b6)

2024-07-24 18:07 UTC, lasgra commented on src/app/shared/components/account-table/account-table.component.html
> +    <nav class="flex flex-column flex-wrap md:flex-row justify-between bg-white border-b" aria-label="Table navigation">
Tutaj zaczyna sie jazdy bez trzymanki

2024-07-25 17:38 UTC, Majkoo requested changes
keep it up gj

2024-07-25 17:38 UTC, Majkoo commented on src/app/shared/components/text-button/text-button.component.scss
> +    box-shadow: 0px 8px 11px 2px #000000ad;
use tailwind classes instead:


'shadow-sm bg-surface-100'

2024-07-25 17:38 UTC, Majkoo commented on src/app/shared/components/header/header.component.ts
> +      console.log(this.roleId);
rm

2024-07-25 17:38 UTC, Majkoo commented on src/app/shared/components/header/header.component.ts
> +      this.roleId = this.authService.getJwtData()?.roleId
rm redundant backend call, use account$ instead

2024-07-25 17:38 UTC, Majkoo commented on src/app/shared/components/account-table/account-table.component.ts
> +  checkedEverything(check : boolean){
check instead of checked

2024-07-25 17:38 UTC, Majkoo commented on src/app/shared/components/account-table/account-table.component.ts
> +  changePageSize(event : Event){
same as below

2024-07-25 17:38 UTC, Majkoo commented on src/app/shared/components/account-table/account-table.component.ts
> +  private sortByNameMap: { [key: string]: string } = {
map(PropertyNamesToDisplay)Names?

2024-07-25 17:38 UTC, Majkoo commented on src/app/layouts/table-layout/table-layout.component.html
> +  <div class="p-3 overflow-auto" style="width: 765px;">
use `tailwind.config.js/theme/screens` values

2024-07-31 17:39 UTC, Majkoo requested changes

2024-07-31 17:39 UTC, Majkoo commented on src/app/shared/components/account-table/account-table.component.ts
> +    console.log(this.sortBy);
rm console log

2024-08-01 08:59 UTC, lasgra commented on src/app/shared/components/account-table/account-table.component.ts
> +    console.log(this.sortBy);
imposible to do

2024-08-01 09:41 UTC, Majkoo approved these changes

2024-08-01 09:43 UTC, merged