Ficzyr/moderate photos
Majkoo/PicturesUI pull request #23
Opened 2024-08-01 13:04 UTC by lasgra

Cool little small tiny feature 
![image](https://github.com/user-attachments/assets/7f52e6c2-1f81-43d1-86b2-616b2753325d)

2024-08-01 13:04 UTC, lasgra commented on src/app/services/api/account/account-pictures.service.ts
>  import { Injectable } from '@angular/core';
to jest ten plik co zmieniłem importy

2024-08-01 13:13 UTC, Majkoo requested changes

2024-08-01 13:13 UTC, Majkoo commented on src/app/services/api/account/auth.service.ts
> +  get isAdmin(): boolean {
name doesnt match behavior

2024-08-01 13:13 UTC, Majkoo commented on src/app/shared/components/query-modal/viewPicture/view-picture-modal.component.html
> +              <pp-mod-btn [pic]="pic"></pp-mod-btn>
name doesnt match purpose

2024-08-01 13:14 UTC, Majkoo commented on src/app/services/api/account/auth.service.ts
> +  get isAdmin(): boolean {
my preference is to have two methods: isAdmin, isModerator. Then in corresponding places its just if (isAdmin || isModerator) that is just readable

2024-08-19 12:09 UTC, lasgra commented
Turns out it wasn't little feature,

![image](https://github.com/user-attachments/assets/06a02d12-3d57-4b23-972c-b4699884d83e)
Added moderation buttons. One to delete image, and other to ban user, and automatically delete all of user's images

![image](https://github.com/user-attachments/assets/f506acb6-21f9-4275-a2a7-ffd6b2d45b88)
Added settings functionality, that uses localstorage to keep data, and settingsService to access them.

2 new buttons in settings, one to turn off or on moderation buttons, and one to show something special.

2 new components, settings-option for lightings speed adding new options to settings, and switch-btn which looks amazing,

and fixed few random things I found

2024-08-19 12:10 UTC, lasgra commented on src/app/shared/components/query-modal/viewPicture/view-picture-modal.component.html
> +              <pp-mod-btn [pic]="pic"></pp-mod-btn>
it matches purpose very well

2024-08-19 12:12 UTC, lasgra commented on src/app/services/api/account/auth.service.ts
> +  get isAdmin(): boolean {
changed name to isModerator, it's well fitted because I don't need to make a ton of fixes, and technically admin is also a moderator

2024-08-19 17:40 UTC, Majkoo commented on src/app/services/api/account/auth.service.ts
> +  get isAdmin(): boolean {
no

2024-08-19 17:45 UTC, Majkoo commented on src/app/services/api/picture/picture.service.ts
> +    return this.httpClient.delete<String>(`${environment.apiUrl}/picture/${id}`)
uppercase String?

2024-08-19 17:57 UTC, Majkoo requested changes
splendid ✨

2024-08-19 17:57 UTC, Majkoo commented on src/app/shared/components/setting-option/setting-option.component.ts
> +  @Input() changeFlipState: boolean = false;
value, switchValue, state,

2024-08-19 17:57 UTC, Majkoo commented on src/app/shared/components/setting-option/setting-option.component.ts
> +  @Output() switchFlipped: EventEmitter<boolean> = new EventEmitter<boolean>();
switched, valueChanged

2024-08-19 17:57 UTC, Majkoo commented on src/app/shared/components/switch-btn/switch-btn.component.ts
> +  ngOnInit(){
console log rm

2024-08-19 17:57 UTC, Majkoo commented on src/app/shared/components/switch-btn/switch-btn.component.ts
> +  @Input() flipped: boolean = false;
adjust naming

2024-08-19 17:57 UTC, Majkoo approved these changes

2024-08-19 17:58 UTC, merged